-- Manual Migration Script for Booking System
-- Generated by @Architect for T003 task
-- Date: 2026-04-15
-- 
-- IMPORTANT: This script contains SQL that Prisma Migrate cannot generate automatically
-- Run this script after initial Prisma migration

-- ============================================
-- 1. Partial Unique Index for High-Concurrency Booking
-- ============================================

-- This index ensures atomic slot allocation by preventing double-booking
-- It only applies to active bookings (PENDING, CONFIRMED, COMPLETED)
CREATE UNIQUE INDEX IF NOT EXISTS appointment_slot_occupied 
ON bookings(time_slot_id, appointment_date, slot_sequence)
WHERE status IN ('PENDING', 'CONFIRMED', 'COMPLETED');

COMMENT ON INDEX appointment_slot_occupied IS 'Ensures atomic booking by preventing double-booking of the same time slot sequence';

-- ============================================
-- 2. Function and Trigger for Automatic Sequence Increment
-- ============================================

-- Function to increment current_sequence in time_slots when a booking is created
CREATE OR REPLACE FUNCTION increment_time_slot_sequence()
RETURNS TRIGGER AS $$
BEGIN
  -- Only increment for PENDING or CONFIRMED bookings
  IF NEW.status IN ('PENDING', 'CONFIRMED') THEN
    UPDATE time_slots 
    SET current_sequence = current_sequence + 1
    WHERE id = NEW.time_slot_id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to automatically increment sequence on booking creation
DROP TRIGGER IF EXISTS booking_created_trigger ON bookings;
CREATE TRIGGER booking_created_trigger
AFTER INSERT ON bookings
FOR EACH ROW
EXECUTE FUNCTION increment_time_slot_sequence();

-- ============================================
-- 3. Additional Performance Indexes
-- ============================================

-- Index for fast time slot queries by service and date range
CREATE INDEX IF NOT EXISTS idx_time_slots_service_date 
ON time_slots(service_id, start_time, end_time);

-- Index for user booking history
CREATE INDEX IF NOT EXISTS idx_bookings_user_date 
ON bookings(user_id, appointment_date DESC);

-- Index for time slot availability queries
CREATE INDEX IF NOT EXISTS idx_bookings_slot_status 
ON bookings(time_slot_id, appointment_date, status);

-- Index for service filtering
CREATE INDEX IF NOT EXISTS idx_services_active 
ON services(active, created_at DESC);

-- Index for user lookup
CREATE INDEX IF NOT EXISTS idx_users_email 
ON users(email);

-- ============================================
-- 4. View for Available Time Slots
-- ============================================

-- Materialized view for available time slots (can be refreshed periodically)
-- Or regular view for real-time queries (slower but up-to-date)
CREATE OR REPLACE VIEW available_time_slots AS
SELECT 
  ts.id,
  ts.service_id,
  s.name as service_name,
  ts.start_time,
  ts.end_time,
  ts.capacity,
  COALESCE(b.booked_count, 0) as booked_count,
  ts.capacity - COALESCE(b.booked_count, 0) as available_slots,
  ts.current_sequence,
  ts.created_at
FROM time_slots ts
JOIN services s ON ts.service_id = s.id
LEFT JOIN (
  SELECT 
    time_slot_id,
    appointment_date::date as slot_date,
    COUNT(*) as booked_count
  FROM bookings
  WHERE status IN ('PENDING', 'CONFIRMED')
  GROUP BY time_slot_id, appointment_date::date
) b ON ts.id = b.time_slot_id 
  AND ts.start_time::date = b.slot_date
WHERE s.active = true
  AND ts.start_time > NOW()
ORDER BY ts.start_time;

COMMENT ON VIEW available_time_slots IS 'Real-time view of available time slots with capacity information';

-- ============================================
-- 5. Row-Level Security (Optional, for multi-tenant)
-- ============================================

-- Enable Row Level Security if needed for multi-tenant architecture
-- ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY user_bookings_policy ON bookings 
--   FOR ALL USING (user_id = current_user_id());

-- ============================================
-- 6. Database Extensions
-- ============================================

-- Enable UUID extension if not already enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Enable pg_stat_statements for query performance monitoring (requires superuser)
-- CREATE EXTENSION IF NOT EXISTS pg_stat_statements;

-- ============================================
-- 7. Seed Data Insertion Functions
-- ============================================

-- Function to generate sample time slots (for testing)
CREATE OR REPLACE FUNCTION generate_sample_time_slots(
  p_service_id UUID,
  p_start_date DATE,
  p_days INTEGER
)
RETURNS INTEGER AS $$
DECLARE
  v_counter INTEGER := 0;
  v_current_date DATE;
  v_start_time TIMESTAMP;
  v_end_time TIMESTAMP;
BEGIN
  FOR i IN 0..(p_days - 1) LOOP
    v_current_date := p_start_date + i;
    
    -- Generate time slots from 9 AM to 5 PM, every 30 minutes
    FOR hour IN 9..16 LOOP
      FOR minute IN 0..1 LOOP
        v_start_time := v_current_date + (hour * INTERVAL '1 hour') + (minute * 30 * INTERVAL '1 minute');
        v_end_time := v_start_time + INTERVAL '30 minutes';
        
        INSERT INTO time_slots (
          id, service_id, start_time, end_time, 
          capacity, current_sequence, created_at, updated_at
        ) VALUES (
          uuid_generate_v4(),
          p_service_id,
          v_start_time,
          v_end_time,
          1 + floor(random() * 3), -- Random capacity 1-3
          0,
          NOW(),
          NOW()
        );
        
        v_counter := v_counter + 1;
      END LOOP;
    END LOOP;
  END LOOP;
  
  RETURN v_counter;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION generate_sample_time_slots IS 'Helper function to generate sample time slots for testing';

-- ============================================
-- 8. Audit Logging Setup (Optional)
-- ============================================

-- Create audit log table if needed
CREATE TABLE IF NOT EXISTS audit_logs (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  table_name TEXT NOT NULL,
  record_id UUID NOT NULL,
  operation TEXT NOT NULL CHECK (operation IN ('INSERT', 'UPDATE', 'DELETE')),
  old_data JSONB,
  new_data JSONB,
  changed_by UUID REFERENCES users(id),
  changed_at TIMESTAMP DEFAULT NOW(),
  ip_address INET,
  user_agent TEXT
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_record ON audit_logs(table_name, record_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_changed_at ON audit_logs(changed_at DESC);

-- ============================================
-- 9. Migration Verification Queries
-- ============================================

-- Verify partial unique index exists
SELECT 
  indexname,
  indexdef
FROM pg_indexes
WHERE tablename = 'bookings'
  AND indexname = 'appointment_slot_occupied';

-- Verify trigger exists
SELECT 
  tgname as trigger_name,
  tgtype as trigger_type
FROM pg_trigger
WHERE tgname = 'booking_created_trigger';

-- Verify view exists
SELECT 
  table_name,
  view_definition
FROM information_schema.views
WHERE table_name = 'available_time_slots';

-- ============================================
-- Migration Complete
-- ============================================

-- Print summary
DO $$
BEGIN
  RAISE NOTICE '✅ Manual migration completed successfully';
  RAISE NOTICE '   - Partial unique index created for high-concurrency booking';
  RAISE NOTICE '   - Trigger created for automatic sequence increment';
  RAISE NOTICE '   - Performance indexes created';
  RAISE NOTICE '   - Available time slots view created';
END $$;