-- Initial migration for Booking System
-- Generated by Qoder
-- Schema Version: 2.0.0

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";

-- ============================================
-- Enums (aligned with Prisma schema v2.0.0)
-- ============================================

CREATE TYPE "UserType" AS ENUM ('CUSTOMER', 'ADMIN', 'SUPER_ADMIN');
CREATE TYPE "UserStatus" AS ENUM ('ACTIVE', 'INACTIVE', 'BLOCKED');
CREATE TYPE "AppointmentStatus" AS ENUM ('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', 'EXPIRED');
CREATE TYPE "NotificationType" AS ENUM ('SMS', 'EMAIL', 'WECHAT', 'PUSH', 'SYSTEM');
CREATE TYPE "NotificationStatus" AS ENUM ('PENDING', 'SENT', 'FAILED', 'READ', 'QUEUED');

-- ============================================
-- User Model
-- ============================================

CREATE TABLE "users" (
    "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "name" VARCHAR(255) NOT NULL,
    "phone" VARCHAR(50) UNIQUE,
    "email" VARCHAR(255) UNIQUE,
    "user_type" "UserType" NOT NULL DEFAULT 'CUSTOMER',
    "status" "UserStatus" NOT NULL DEFAULT 'ACTIVE',
    "last_login_at" TIMESTAMP,
    "device_info" JSONB,
    "remarks" TEXT,
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX "users_email_idx" ON "users"("email");
CREATE INDEX "users_phone_idx" ON "users"("phone");
CREATE INDEX "users_user_type_status_idx" ON "users"("user_type", "status");
CREATE INDEX "users_created_at_idx" ON "users"("created_at");
CREATE INDEX "users_last_login_at_idx" ON "users"("last_login_at");

-- ============================================
-- User Session Model
-- ============================================

CREATE TABLE "user_sessions" (
    "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "user_id" UUID NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
    "session_token" VARCHAR(500) NOT NULL UNIQUE,
    "refresh_token" VARCHAR(500) NOT NULL UNIQUE,
    "expires_at" TIMESTAMP NOT NULL,
    "refresh_expires_at" TIMESTAMP,
    "ip_address" INET,
    "user_agent" TEXT,
    "device_info" JSONB,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX "user_sessions_user_id_idx" ON "user_sessions"("user_id");
CREATE INDEX "user_sessions_session_token_idx" ON "user_sessions"("session_token");
CREATE INDEX "user_sessions_refresh_token_idx" ON "user_sessions"("refresh_token");
CREATE INDEX "user_sessions_expires_at_idx" ON "user_sessions"("expires_at");

-- ============================================
-- Service Category Model
-- ============================================

CREATE TABLE "service_categories" (
    "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "name" VARCHAR(255) NOT NULL UNIQUE,
    "description" TEXT,
    "icon_url" VARCHAR(255),
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "display_order" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX "service_categories_name_idx" ON "service_categories"("name");
CREATE INDEX "service_categories_is_active_idx" ON "service_categories"("is_active");
CREATE INDEX "service_categories_display_order_idx" ON "service_categories"("display_order");
CREATE INDEX "service_categories_is_active_display_order_idx" ON "service_categories"("is_active", "display_order");

-- ============================================
-- Service Model
-- ============================================

CREATE TABLE "services" (
    "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "category_id" UUID NOT NULL REFERENCES "service_categories"("id"),
    "name" VARCHAR(255) NOT NULL,
    "description" TEXT,
    "duration_minutes" INTEGER NOT NULL DEFAULT 60,
    "price" DECIMAL(10, 2),
    "image_url" VARCHAR(255),
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "display_order" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX "services_category_id_idx" ON "services"("category_id");
CREATE INDEX "services_name_idx" ON "services"("name");
CREATE INDEX "services_is_active_idx" ON "services"("is_active");
CREATE INDEX "services_display_order_idx" ON "services"("display_order");
CREATE INDEX "services_category_id_is_active_idx" ON "services"("category_id", "is_active");
CREATE INDEX "services_price_idx" ON "services"("price");

-- ============================================
-- Time Slot Model
-- ============================================

CREATE TABLE "time_slots" (
    "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "service_id" UUID NOT NULL REFERENCES "services"("id"),
    "slot_time" VARCHAR(255) NOT NULL UNIQUE,
    "duration_minutes" INTEGER NOT NULL DEFAULT 60,
    "capacity" INTEGER NOT NULL DEFAULT 1,
    "current_sequence" INTEGER NOT NULL DEFAULT 0,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "display_order" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX "time_slots_service_id_idx" ON "time_slots"("service_id");
CREATE INDEX "time_slots_slot_time_idx" ON "time_slots"("slot_time");
CREATE INDEX "time_slots_is_active_idx" ON "time_slots"("is_active");
CREATE INDEX "time_slots_display_order_idx" ON "time_slots"("display_order");
CREATE INDEX "time_slots_capacity_seq_idx" ON "time_slots"("capacity", "current_sequence");
-- Partial index for active time slots
CREATE INDEX "time_slots_active_capacity_seq_idx" ON "time_slots"("capacity", "current_sequence") WHERE "is_active" = true;

-- ============================================
-- Appointment Model
-- ============================================

CREATE TABLE "appointments" (
    "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "user_id" UUID NOT NULL REFERENCES "users"("id"),
    "time_slot_id" UUID NOT NULL REFERENCES "time_slots"("id"),
    "service_id" UUID NOT NULL REFERENCES "services"("id"),
    "appointment_number" VARCHAR(255) NOT NULL UNIQUE,
    "appointment_date" TIMESTAMP NOT NULL,
    "slot_sequence" INTEGER NOT NULL DEFAULT 0,
    "status" "AppointmentStatus" NOT NULL DEFAULT 'PENDING',
    "customer_info" JSONB NOT NULL,
    "remarks" TEXT,
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX "appointments_user_id_appointment_date_idx" ON "appointments"("user_id", "appointment_date");
CREATE INDEX "appointments_time_slot_id_appointment_date_status_idx" ON "appointments"("time_slot_id", "appointment_date", "status");
CREATE INDEX "appointments_appointment_number_idx" ON "appointments"("appointment_number");
CREATE INDEX "appointments_status_appointment_date_idx" ON "appointments"("status", "appointment_date");
-- Unique constraint for slot occupation
CREATE UNIQUE INDEX "appointment_slot_occupied" ON "appointments"("time_slot_id", "appointment_date", "slot_sequence");

-- ============================================
-- Appointment History Model
-- ============================================

CREATE TABLE "appointment_histories" (
    "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "appointment_id" UUID NOT NULL REFERENCES "appointments"("id") ON DELETE CASCADE,
    "action" VARCHAR(255) NOT NULL,
    "previous_status" "AppointmentStatus",
    "new_status" "AppointmentStatus",
    "change_reason" VARCHAR(255),
    "performed_by" VARCHAR(255) NOT NULL,
    "performed_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    "metadata" JSONB
);

CREATE INDEX "appointment_histories_appointment_id_idx" ON "appointment_histories"("appointment_id");
CREATE INDEX "appointment_histories_performed_at_idx" ON "appointment_histories"("performed_at");
CREATE INDEX "appointment_histories_action_idx" ON "appointment_histories"("action");
CREATE INDEX "appointment_histories_appt_date_desc_idx" ON "appointment_histories"("appointment_id", "performed_at" DESC);

-- ============================================
-- Notification Model
-- ============================================

CREATE TABLE "notifications" (
    "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "user_id" UUID NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
    "appointment_id" UUID REFERENCES "appointments"("id") ON DELETE CASCADE,
    "type" "NotificationType" NOT NULL,
    "title" VARCHAR(255) NOT NULL,
    "content" TEXT NOT NULL,
    "is_read" BOOLEAN NOT NULL DEFAULT false,
    "status" "NotificationStatus" NOT NULL DEFAULT 'PENDING',
    "metadata" JSONB,
    "scheduled_at" TIMESTAMP,
    "sent_at" TIMESTAMP,
    "retry_count" INTEGER NOT NULL DEFAULT 0,
    "last_error" TEXT,
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX "notifications_user_id_idx" ON "notifications"("user_id");
CREATE INDEX "notifications_user_id_is_read_idx" ON "notifications"("user_id", "is_read");
CREATE INDEX "notifications_status_idx" ON "notifications"("status");
CREATE INDEX "notifications_status_scheduled_at_idx" ON "notifications"("status", "scheduled_at");
CREATE INDEX "notifications_type_idx" ON "notifications"("type");
CREATE INDEX "notifications_created_at_idx" ON "notifications"("created_at");
CREATE INDEX "notifications_appointment_id_idx" ON "notifications"("appointment_id");

-- ============================================
-- Activity Log Model
-- ============================================

CREATE TABLE "activity_logs" (
    "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "user_id" UUID REFERENCES "users"("id") ON DELETE SET NULL,
    "action" VARCHAR(255) NOT NULL,
    "resource_type" VARCHAR(255) NOT NULL,
    "resource_id" VARCHAR(255),
    "ip_address" VARCHAR(50),
    "user_agent" TEXT,
    "metadata" JSONB,
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX "activity_logs_user_id_idx" ON "activity_logs"("user_id");
CREATE INDEX "activity_logs_action_idx" ON "activity_logs"("action");
CREATE INDEX "activity_logs_resource_type_idx" ON "activity_logs"("resource_type");
CREATE INDEX "activity_logs_resource_id_idx" ON "activity_logs"("resource_id");
CREATE INDEX "activity_logs_created_at_idx" ON "activity_logs"("created_at");
CREATE INDEX "activity_logs_user_created_desc_idx" ON "activity_logs"("user_id", "created_at" DESC);

-- ============================================
-- System Setting Model
-- ============================================

CREATE TABLE "system_settings" (
    "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "setting_key" VARCHAR(255) NOT NULL UNIQUE,
    "setting_value" TEXT NOT NULL,
    "setting_type" VARCHAR(50) NOT NULL DEFAULT 'STRING',
    "category" VARCHAR(100) NOT NULL DEFAULT 'GENERAL',
    "description" TEXT,
    "is_protected" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX "system_settings_setting_key_idx" ON "system_settings"("setting_key");
CREATE INDEX "system_settings_category_idx" ON "system_settings"("category");

-- ============================================
-- System Log Model
-- ============================================

CREATE TABLE "system_logs" (
    "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "level" VARCHAR(50) NOT NULL,
    "message" TEXT NOT NULL,
    "context" JSONB,
    "ip_address" VARCHAR(50),
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX "system_logs_level_idx" ON "system_logs"("level");
CREATE INDEX "system_logs_created_at_idx" ON "system_logs"("created_at");
CREATE INDEX "system_logs_level_created_at_idx" ON "system_logs"("level", "created_at");
